# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  RESCOMP = windres
  TARGETDIR = bin/Debug
  TARGET = $(TARGETDIR)/libblas.a
  OBJDIR = obj/Debug/blas
  DEFINES += -DDEBUG -DUSE_CLOCK -DNO_BLAS_WRAP
  INCLUDES += -I../../core/include -I../../third/concurrentqueue -I../../third/EASTL/include -I../../third/clapack-3.2.1/INCLUDE -I../../third/clapack-3.2.1/F2CLIBS/libf2c
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -fPIC -Wno-multichar -fshort-wchar -g -rdynamic  -std=gnu99
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CFLAGS)
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release)
  RESCOMP = windres
  TARGETDIR = bin/Release
  TARGET = $(TARGETDIR)/libblas.a
  OBJDIR = obj/Release/blas
  DEFINES += -DNDEBUG -DUSE_CLOCK -DNO_BLAS_WRAP
  INCLUDES += -I../../core/include -I../../third/concurrentqueue -I../../third/EASTL/include -I../../third/clapack-3.2.1/INCLUDE -I../../third/clapack-3.2.1/F2CLIBS/libf2c
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -Wno-multichar -fshort-wchar -std=gnu99
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CFLAGS)
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/caxpy.o \
	$(OBJDIR)/ccopy.o \
	$(OBJDIR)/cdotc.o \
	$(OBJDIR)/cdotu.o \
	$(OBJDIR)/cgbmv.o \
	$(OBJDIR)/cgemm.o \
	$(OBJDIR)/cgemv.o \
	$(OBJDIR)/cgerc.o \
	$(OBJDIR)/cgeru.o \
	$(OBJDIR)/chbmv.o \
	$(OBJDIR)/chemm.o \
	$(OBJDIR)/chemv.o \
	$(OBJDIR)/cher.o \
	$(OBJDIR)/cher2.o \
	$(OBJDIR)/cher2k.o \
	$(OBJDIR)/cherk.o \
	$(OBJDIR)/chpmv.o \
	$(OBJDIR)/chpr.o \
	$(OBJDIR)/chpr2.o \
	$(OBJDIR)/crotg.o \
	$(OBJDIR)/cscal.o \
	$(OBJDIR)/csrot.o \
	$(OBJDIR)/csscal.o \
	$(OBJDIR)/cswap.o \
	$(OBJDIR)/csymm.o \
	$(OBJDIR)/csyr2k.o \
	$(OBJDIR)/csyrk.o \
	$(OBJDIR)/ctbmv.o \
	$(OBJDIR)/ctbsv.o \
	$(OBJDIR)/ctpmv.o \
	$(OBJDIR)/ctpsv.o \
	$(OBJDIR)/ctrmm.o \
	$(OBJDIR)/ctrmv.o \
	$(OBJDIR)/ctrsm.o \
	$(OBJDIR)/ctrsv.o \
	$(OBJDIR)/dasum.o \
	$(OBJDIR)/daxpy.o \
	$(OBJDIR)/dcabs1.o \
	$(OBJDIR)/dcopy.o \
	$(OBJDIR)/ddot.o \
	$(OBJDIR)/dgbmv.o \
	$(OBJDIR)/dgemm.o \
	$(OBJDIR)/dgemv.o \
	$(OBJDIR)/dger.o \
	$(OBJDIR)/dnrm2.o \
	$(OBJDIR)/drot.o \
	$(OBJDIR)/drotg.o \
	$(OBJDIR)/drotm.o \
	$(OBJDIR)/drotmg.o \
	$(OBJDIR)/dsbmv.o \
	$(OBJDIR)/dscal.o \
	$(OBJDIR)/dsdot.o \
	$(OBJDIR)/dspmv.o \
	$(OBJDIR)/dspr.o \
	$(OBJDIR)/dspr2.o \
	$(OBJDIR)/dswap.o \
	$(OBJDIR)/dsymm.o \
	$(OBJDIR)/dsymv.o \
	$(OBJDIR)/dsyr.o \
	$(OBJDIR)/dsyr2.o \
	$(OBJDIR)/dsyr2k.o \
	$(OBJDIR)/dsyrk.o \
	$(OBJDIR)/dtbmv.o \
	$(OBJDIR)/dtbsv.o \
	$(OBJDIR)/dtpmv.o \
	$(OBJDIR)/dtpsv.o \
	$(OBJDIR)/dtrmm.o \
	$(OBJDIR)/dtrmv.o \
	$(OBJDIR)/dtrsm.o \
	$(OBJDIR)/dtrsv.o \
	$(OBJDIR)/dzasum.o \
	$(OBJDIR)/dznrm2.o \
	$(OBJDIR)/icamax.o \
	$(OBJDIR)/idamax.o \
	$(OBJDIR)/isamax.o \
	$(OBJDIR)/izamax.o \
	$(OBJDIR)/lsame.o \
	$(OBJDIR)/sasum.o \
	$(OBJDIR)/saxpy.o \
	$(OBJDIR)/scabs1.o \
	$(OBJDIR)/scasum.o \
	$(OBJDIR)/scnrm2.o \
	$(OBJDIR)/scopy.o \
	$(OBJDIR)/sdot.o \
	$(OBJDIR)/sdsdot.o \
	$(OBJDIR)/sgbmv.o \
	$(OBJDIR)/sgemm.o \
	$(OBJDIR)/sgemv.o \
	$(OBJDIR)/sger.o \
	$(OBJDIR)/snrm2.o \
	$(OBJDIR)/srot.o \
	$(OBJDIR)/srotg.o \
	$(OBJDIR)/srotm.o \
	$(OBJDIR)/srotmg.o \
	$(OBJDIR)/ssbmv.o \
	$(OBJDIR)/sscal.o \
	$(OBJDIR)/sspmv.o \
	$(OBJDIR)/sspr.o \
	$(OBJDIR)/sspr2.o \
	$(OBJDIR)/sswap.o \
	$(OBJDIR)/ssymm.o \
	$(OBJDIR)/ssymv.o \
	$(OBJDIR)/ssyr.o \
	$(OBJDIR)/ssyr2.o \
	$(OBJDIR)/ssyr2k.o \
	$(OBJDIR)/ssyrk.o \
	$(OBJDIR)/stbmv.o \
	$(OBJDIR)/stbsv.o \
	$(OBJDIR)/stpmv.o \
	$(OBJDIR)/stpsv.o \
	$(OBJDIR)/strmm.o \
	$(OBJDIR)/strmv.o \
	$(OBJDIR)/strsm.o \
	$(OBJDIR)/strsv.o \
	$(OBJDIR)/xerbla.o \
	$(OBJDIR)/xerbla_array.o \
	$(OBJDIR)/zaxpy.o \
	$(OBJDIR)/zcopy.o \
	$(OBJDIR)/zdotc.o \
	$(OBJDIR)/zdotu.o \
	$(OBJDIR)/zdrot.o \
	$(OBJDIR)/zdscal.o \
	$(OBJDIR)/zgbmv.o \
	$(OBJDIR)/zgemm.o \
	$(OBJDIR)/zgemv.o \
	$(OBJDIR)/zgerc.o \
	$(OBJDIR)/zgeru.o \
	$(OBJDIR)/zhbmv.o \
	$(OBJDIR)/zhemm.o \
	$(OBJDIR)/zhemv.o \
	$(OBJDIR)/zher.o \
	$(OBJDIR)/zher2.o \
	$(OBJDIR)/zher2k.o \
	$(OBJDIR)/zherk.o \
	$(OBJDIR)/zhpmv.o \
	$(OBJDIR)/zhpr.o \
	$(OBJDIR)/zhpr2.o \
	$(OBJDIR)/zrotg.o \
	$(OBJDIR)/zscal.o \
	$(OBJDIR)/zswap.o \
	$(OBJDIR)/zsymm.o \
	$(OBJDIR)/zsyr2k.o \
	$(OBJDIR)/zsyrk.o \
	$(OBJDIR)/ztbmv.o \
	$(OBJDIR)/ztbsv.o \
	$(OBJDIR)/ztpmv.o \
	$(OBJDIR)/ztpsv.o \
	$(OBJDIR)/ztrmm.o \
	$(OBJDIR)/ztrmv.o \
	$(OBJDIR)/ztrsm.o \
	$(OBJDIR)/ztrsv.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking blas
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning blas
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH)
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/caxpy.o: ../../third/clapack-3.2.1/BLAS/SRC/caxpy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ccopy.o: ../../third/clapack-3.2.1/BLAS/SRC/ccopy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cdotc.o: ../../third/clapack-3.2.1/BLAS/SRC/cdotc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cdotu.o: ../../third/clapack-3.2.1/BLAS/SRC/cdotu.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/cgbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgemm.o: ../../third/clapack-3.2.1/BLAS/SRC/cgemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgemv.o: ../../third/clapack-3.2.1/BLAS/SRC/cgemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgerc.o: ../../third/clapack-3.2.1/BLAS/SRC/cgerc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgeru.o: ../../third/clapack-3.2.1/BLAS/SRC/cgeru.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/chbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chemm.o: ../../third/clapack-3.2.1/BLAS/SRC/chemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chemv.o: ../../third/clapack-3.2.1/BLAS/SRC/chemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cher.o: ../../third/clapack-3.2.1/BLAS/SRC/cher.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cher2.o: ../../third/clapack-3.2.1/BLAS/SRC/cher2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cher2k.o: ../../third/clapack-3.2.1/BLAS/SRC/cher2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cherk.o: ../../third/clapack-3.2.1/BLAS/SRC/cherk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/chpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chpr.o: ../../third/clapack-3.2.1/BLAS/SRC/chpr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/chpr2.o: ../../third/clapack-3.2.1/BLAS/SRC/chpr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crotg.o: ../../third/clapack-3.2.1/BLAS/SRC/crotg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cscal.o: ../../third/clapack-3.2.1/BLAS/SRC/cscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/csrot.o: ../../third/clapack-3.2.1/BLAS/SRC/csrot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/csscal.o: ../../third/clapack-3.2.1/BLAS/SRC/csscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cswap.o: ../../third/clapack-3.2.1/BLAS/SRC/cswap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/csymm.o: ../../third/clapack-3.2.1/BLAS/SRC/csymm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/csyr2k.o: ../../third/clapack-3.2.1/BLAS/SRC/csyr2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/csyrk.o: ../../third/clapack-3.2.1/BLAS/SRC/csyrk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctbsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctbsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctpsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctpsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctrmm.o: ../../third/clapack-3.2.1/BLAS/SRC/ctrmm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctrmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctrmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctrsm.o: ../../third/clapack-3.2.1/BLAS/SRC/ctrsm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctrsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ctrsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dasum.o: ../../third/clapack-3.2.1/BLAS/SRC/dasum.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/daxpy.o: ../../third/clapack-3.2.1/BLAS/SRC/daxpy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dcabs1.o: ../../third/clapack-3.2.1/BLAS/SRC/dcabs1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dcopy.o: ../../third/clapack-3.2.1/BLAS/SRC/dcopy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ddot.o: ../../third/clapack-3.2.1/BLAS/SRC/ddot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dgbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dgbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dgemm.o: ../../third/clapack-3.2.1/BLAS/SRC/dgemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dgemv.o: ../../third/clapack-3.2.1/BLAS/SRC/dgemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dger.o: ../../third/clapack-3.2.1/BLAS/SRC/dger.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dnrm2.o: ../../third/clapack-3.2.1/BLAS/SRC/dnrm2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/drot.o: ../../third/clapack-3.2.1/BLAS/SRC/drot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/drotg.o: ../../third/clapack-3.2.1/BLAS/SRC/drotg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/drotm.o: ../../third/clapack-3.2.1/BLAS/SRC/drotm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/drotmg.o: ../../third/clapack-3.2.1/BLAS/SRC/drotmg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dsbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dscal.o: ../../third/clapack-3.2.1/BLAS/SRC/dscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsdot.o: ../../third/clapack-3.2.1/BLAS/SRC/dsdot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dspmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dspmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dspr.o: ../../third/clapack-3.2.1/BLAS/SRC/dspr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dspr2.o: ../../third/clapack-3.2.1/BLAS/SRC/dspr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dswap.o: ../../third/clapack-3.2.1/BLAS/SRC/dswap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsymm.o: ../../third/clapack-3.2.1/BLAS/SRC/dsymm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsymv.o: ../../third/clapack-3.2.1/BLAS/SRC/dsymv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsyr.o: ../../third/clapack-3.2.1/BLAS/SRC/dsyr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsyr2.o: ../../third/clapack-3.2.1/BLAS/SRC/dsyr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsyr2k.o: ../../third/clapack-3.2.1/BLAS/SRC/dsyr2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dsyrk.o: ../../third/clapack-3.2.1/BLAS/SRC/dsyrk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtbsv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtbsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtpsv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtpsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtrmm.o: ../../third/clapack-3.2.1/BLAS/SRC/dtrmm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtrmv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtrmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtrsm.o: ../../third/clapack-3.2.1/BLAS/SRC/dtrsm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtrsv.o: ../../third/clapack-3.2.1/BLAS/SRC/dtrsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dzasum.o: ../../third/clapack-3.2.1/BLAS/SRC/dzasum.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dznrm2.o: ../../third/clapack-3.2.1/BLAS/SRC/dznrm2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/icamax.o: ../../third/clapack-3.2.1/BLAS/SRC/icamax.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/idamax.o: ../../third/clapack-3.2.1/BLAS/SRC/idamax.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/isamax.o: ../../third/clapack-3.2.1/BLAS/SRC/isamax.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/izamax.o: ../../third/clapack-3.2.1/BLAS/SRC/izamax.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lsame.o: ../../third/clapack-3.2.1/BLAS/SRC/lsame.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sasum.o: ../../third/clapack-3.2.1/BLAS/SRC/sasum.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/saxpy.o: ../../third/clapack-3.2.1/BLAS/SRC/saxpy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scabs1.o: ../../third/clapack-3.2.1/BLAS/SRC/scabs1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scasum.o: ../../third/clapack-3.2.1/BLAS/SRC/scasum.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scnrm2.o: ../../third/clapack-3.2.1/BLAS/SRC/scnrm2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/scopy.o: ../../third/clapack-3.2.1/BLAS/SRC/scopy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sdot.o: ../../third/clapack-3.2.1/BLAS/SRC/sdot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sdsdot.o: ../../third/clapack-3.2.1/BLAS/SRC/sdsdot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sgbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/sgbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sgemm.o: ../../third/clapack-3.2.1/BLAS/SRC/sgemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sgemv.o: ../../third/clapack-3.2.1/BLAS/SRC/sgemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sger.o: ../../third/clapack-3.2.1/BLAS/SRC/sger.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/snrm2.o: ../../third/clapack-3.2.1/BLAS/SRC/snrm2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/srot.o: ../../third/clapack-3.2.1/BLAS/SRC/srot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/srotg.o: ../../third/clapack-3.2.1/BLAS/SRC/srotg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/srotm.o: ../../third/clapack-3.2.1/BLAS/SRC/srotm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/srotmg.o: ../../third/clapack-3.2.1/BLAS/SRC/srotmg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ssbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sscal.o: ../../third/clapack-3.2.1/BLAS/SRC/sscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sspmv.o: ../../third/clapack-3.2.1/BLAS/SRC/sspmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sspr.o: ../../third/clapack-3.2.1/BLAS/SRC/sspr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sspr2.o: ../../third/clapack-3.2.1/BLAS/SRC/sspr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sswap.o: ../../third/clapack-3.2.1/BLAS/SRC/sswap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssymm.o: ../../third/clapack-3.2.1/BLAS/SRC/ssymm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssymv.o: ../../third/clapack-3.2.1/BLAS/SRC/ssymv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssyr.o: ../../third/clapack-3.2.1/BLAS/SRC/ssyr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssyr2.o: ../../third/clapack-3.2.1/BLAS/SRC/ssyr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssyr2k.o: ../../third/clapack-3.2.1/BLAS/SRC/ssyr2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ssyrk.o: ../../third/clapack-3.2.1/BLAS/SRC/ssyrk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/stbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stbsv.o: ../../third/clapack-3.2.1/BLAS/SRC/stbsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/stpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stpsv.o: ../../third/clapack-3.2.1/BLAS/SRC/stpsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/strmm.o: ../../third/clapack-3.2.1/BLAS/SRC/strmm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/strmv.o: ../../third/clapack-3.2.1/BLAS/SRC/strmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/strsm.o: ../../third/clapack-3.2.1/BLAS/SRC/strsm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/strsv.o: ../../third/clapack-3.2.1/BLAS/SRC/strsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/xerbla.o: ../../third/clapack-3.2.1/BLAS/SRC/xerbla.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/xerbla_array.o: ../../third/clapack-3.2.1/BLAS/SRC/xerbla_array.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zaxpy.o: ../../third/clapack-3.2.1/BLAS/SRC/zaxpy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zcopy.o: ../../third/clapack-3.2.1/BLAS/SRC/zcopy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zdotc.o: ../../third/clapack-3.2.1/BLAS/SRC/zdotc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zdotu.o: ../../third/clapack-3.2.1/BLAS/SRC/zdotu.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zdrot.o: ../../third/clapack-3.2.1/BLAS/SRC/zdrot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zdscal.o: ../../third/clapack-3.2.1/BLAS/SRC/zdscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zgbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/zgbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zgemm.o: ../../third/clapack-3.2.1/BLAS/SRC/zgemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zgemv.o: ../../third/clapack-3.2.1/BLAS/SRC/zgemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zgerc.o: ../../third/clapack-3.2.1/BLAS/SRC/zgerc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zgeru.o: ../../third/clapack-3.2.1/BLAS/SRC/zgeru.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/zhbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhemm.o: ../../third/clapack-3.2.1/BLAS/SRC/zhemm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhemv.o: ../../third/clapack-3.2.1/BLAS/SRC/zhemv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zher.o: ../../third/clapack-3.2.1/BLAS/SRC/zher.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zher2.o: ../../third/clapack-3.2.1/BLAS/SRC/zher2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zher2k.o: ../../third/clapack-3.2.1/BLAS/SRC/zher2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zherk.o: ../../third/clapack-3.2.1/BLAS/SRC/zherk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/zhpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhpr.o: ../../third/clapack-3.2.1/BLAS/SRC/zhpr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zhpr2.o: ../../third/clapack-3.2.1/BLAS/SRC/zhpr2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zrotg.o: ../../third/clapack-3.2.1/BLAS/SRC/zrotg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zscal.o: ../../third/clapack-3.2.1/BLAS/SRC/zscal.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zswap.o: ../../third/clapack-3.2.1/BLAS/SRC/zswap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zsymm.o: ../../third/clapack-3.2.1/BLAS/SRC/zsymm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zsyr2k.o: ../../third/clapack-3.2.1/BLAS/SRC/zsyr2k.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/zsyrk.o: ../../third/clapack-3.2.1/BLAS/SRC/zsyrk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztbmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztbmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztbsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztbsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztpmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztpmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztpsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztpsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztrmm.o: ../../third/clapack-3.2.1/BLAS/SRC/ztrmm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztrmv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztrmv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztrsm.o: ../../third/clapack-3.2.1/BLAS/SRC/ztrsm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ztrsv.o: ../../third/clapack-3.2.1/BLAS/SRC/ztrsv.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif