# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug)
  RESCOMP = windres
  TARGETDIR = bin/Debug
  TARGET = $(TARGETDIR)/libf2c.a
  OBJDIR = obj/Debug/f2c
  DEFINES += -DDEBUG -DUSE_CLOCK -DNO_BLAS_WRAP
  INCLUDES += -I../../core/include -I../../third/concurrentqueue -I../../third/EASTL/include -I../../third/clapack-3.2.1/INCLUDE -I../../third/clapack-3.2.1/F2CLIBS/libf2c
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -fPIC -Wno-multichar -fshort-wchar -g -rdynamic  -std=gnu99
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CFLAGS)
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release)
  RESCOMP = windres
  TARGETDIR = bin/Release
  TARGET = $(TARGETDIR)/libf2c.a
  OBJDIR = obj/Release/f2c
  DEFINES += -DNDEBUG -DUSE_CLOCK -DNO_BLAS_WRAP
  INCLUDES += -I../../core/include -I../../third/concurrentqueue -I../../third/EASTL/include -I../../third/clapack-3.2.1/INCLUDE -I../../third/clapack-3.2.1/F2CLIBS/libf2c
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -fPIC -Wno-multichar -fshort-wchar -std=gnu99
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CFLAGS)
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS +=
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/abort_.o \
	$(OBJDIR)/arithchk.o \
	$(OBJDIR)/backspac.o \
	$(OBJDIR)/c_abs.o \
	$(OBJDIR)/c_cos.o \
	$(OBJDIR)/c_div.o \
	$(OBJDIR)/c_exp.o \
	$(OBJDIR)/c_log.o \
	$(OBJDIR)/c_sin.o \
	$(OBJDIR)/c_sqrt.o \
	$(OBJDIR)/cabs.o \
	$(OBJDIR)/close.o \
	$(OBJDIR)/ctype.o \
	$(OBJDIR)/d_abs.o \
	$(OBJDIR)/d_acos.o \
	$(OBJDIR)/d_asin.o \
	$(OBJDIR)/d_atan.o \
	$(OBJDIR)/d_atn2.o \
	$(OBJDIR)/d_cnjg.o \
	$(OBJDIR)/d_cos.o \
	$(OBJDIR)/d_cosh.o \
	$(OBJDIR)/d_dim.o \
	$(OBJDIR)/d_exp.o \
	$(OBJDIR)/d_imag.o \
	$(OBJDIR)/d_int.o \
	$(OBJDIR)/d_lg10.o \
	$(OBJDIR)/d_log.o \
	$(OBJDIR)/d_mod.o \
	$(OBJDIR)/d_nint.o \
	$(OBJDIR)/d_prod.o \
	$(OBJDIR)/d_sign.o \
	$(OBJDIR)/d_sin.o \
	$(OBJDIR)/d_sinh.o \
	$(OBJDIR)/d_sqrt.o \
	$(OBJDIR)/d_tan.o \
	$(OBJDIR)/d_tanh.o \
	$(OBJDIR)/derf_.o \
	$(OBJDIR)/derfc_.o \
	$(OBJDIR)/dfe.o \
	$(OBJDIR)/dolio.o \
	$(OBJDIR)/dtime_.o \
	$(OBJDIR)/due.o \
	$(OBJDIR)/ef1asc_.o \
	$(OBJDIR)/ef1cmc_.o \
	$(OBJDIR)/endfile.o \
	$(OBJDIR)/erf_.o \
	$(OBJDIR)/erfc_.o \
	$(OBJDIR)/err.o \
	$(OBJDIR)/etime_.o \
	$(OBJDIR)/exit_.o \
	$(OBJDIR)/f77_aloc.o \
	$(OBJDIR)/f77vers.o \
	$(OBJDIR)/fmt.o \
	$(OBJDIR)/fmtlib.o \
	$(OBJDIR)/ftell_.o \
	$(OBJDIR)/getarg_.o \
	$(OBJDIR)/getenv_.o \
	$(OBJDIR)/h_abs.o \
	$(OBJDIR)/h_dim.o \
	$(OBJDIR)/h_dnnt.o \
	$(OBJDIR)/h_indx.o \
	$(OBJDIR)/h_len.o \
	$(OBJDIR)/h_mod.o \
	$(OBJDIR)/h_nint.o \
	$(OBJDIR)/h_sign.o \
	$(OBJDIR)/hl_ge.o \
	$(OBJDIR)/hl_gt.o \
	$(OBJDIR)/hl_le.o \
	$(OBJDIR)/hl_lt.o \
	$(OBJDIR)/i77vers.o \
	$(OBJDIR)/i_abs.o \
	$(OBJDIR)/i_ceiling.o \
	$(OBJDIR)/i_dim.o \
	$(OBJDIR)/i_dnnt.o \
	$(OBJDIR)/i_indx.o \
	$(OBJDIR)/i_len.o \
	$(OBJDIR)/i_len_trim.o \
	$(OBJDIR)/i_mod.o \
	$(OBJDIR)/i_nint.o \
	$(OBJDIR)/i_sign.o \
	$(OBJDIR)/iargc_.o \
	$(OBJDIR)/iio.o \
	$(OBJDIR)/ilnw.o \
	$(OBJDIR)/inquire.o \
	$(OBJDIR)/l_ge.o \
	$(OBJDIR)/l_gt.o \
	$(OBJDIR)/l_le.o \
	$(OBJDIR)/l_lt.o \
	$(OBJDIR)/lbitbits.o \
	$(OBJDIR)/lbitshft.o \
	$(OBJDIR)/lread.o \
	$(OBJDIR)/lwrite.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/open.o \
	$(OBJDIR)/pow_ci.o \
	$(OBJDIR)/pow_dd.o \
	$(OBJDIR)/pow_di.o \
	$(OBJDIR)/pow_hh.o \
	$(OBJDIR)/pow_ii.o \
	$(OBJDIR)/pow_ri.o \
	$(OBJDIR)/pow_zi.o \
	$(OBJDIR)/pow_zz.o \
	$(OBJDIR)/r_abs.o \
	$(OBJDIR)/r_acos.o \
	$(OBJDIR)/r_asin.o \
	$(OBJDIR)/r_atan.o \
	$(OBJDIR)/r_atn2.o \
	$(OBJDIR)/r_cnjg.o \
	$(OBJDIR)/r_cos.o \
	$(OBJDIR)/r_cosh.o \
	$(OBJDIR)/r_dim.o \
	$(OBJDIR)/r_exp.o \
	$(OBJDIR)/r_imag.o \
	$(OBJDIR)/r_int.o \
	$(OBJDIR)/r_lg10.o \
	$(OBJDIR)/r_log.o \
	$(OBJDIR)/r_mod.o \
	$(OBJDIR)/r_nint.o \
	$(OBJDIR)/r_sign.o \
	$(OBJDIR)/r_sin.o \
	$(OBJDIR)/r_sinh.o \
	$(OBJDIR)/r_sqrt.o \
	$(OBJDIR)/r_tan.o \
	$(OBJDIR)/r_tanh.o \
	$(OBJDIR)/rdfmt.o \
	$(OBJDIR)/rewind.o \
	$(OBJDIR)/rsfe.o \
	$(OBJDIR)/rsli.o \
	$(OBJDIR)/rsne.o \
	$(OBJDIR)/s_cat.o \
	$(OBJDIR)/s_cmp.o \
	$(OBJDIR)/s_copy.o \
	$(OBJDIR)/s_paus.o \
	$(OBJDIR)/s_rnge.o \
	$(OBJDIR)/s_stop.o \
	$(OBJDIR)/sfe.o \
	$(OBJDIR)/sig_die.o \
	$(OBJDIR)/signal_.o \
	$(OBJDIR)/signbit.o \
	$(OBJDIR)/sue.o \
	$(OBJDIR)/system_.o \
	$(OBJDIR)/typesize.o \
	$(OBJDIR)/uio.o \
	$(OBJDIR)/uninit.o \
	$(OBJDIR)/util.o \
	$(OBJDIR)/wref.o \
	$(OBJDIR)/wrtfmt.o \
	$(OBJDIR)/wsfe.o \
	$(OBJDIR)/wsle.o \
	$(OBJDIR)/wsne.o \
	$(OBJDIR)/xwsne.o \
	$(OBJDIR)/z_abs.o \
	$(OBJDIR)/z_cos.o \
	$(OBJDIR)/z_div.o \
	$(OBJDIR)/z_exp.o \
	$(OBJDIR)/z_log.o \
	$(OBJDIR)/z_sin.o \
	$(OBJDIR)/z_sqrt.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking f2c
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning f2c
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH)
$(GCH): $(PCH)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/abort_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/abort_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/arithchk.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/arithchk.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/backspac.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/backspac.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_cos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_cos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_div.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_div.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_exp.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_exp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_log.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_log.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_sin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_sin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/c_sqrt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/c_sqrt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cabs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/cabs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/close.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/close.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ctype.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/ctype.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_acos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_acos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_asin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_asin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_atan.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_atan.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_atn2.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_atn2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_cnjg.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_cnjg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_cos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_cos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_cosh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_cosh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_dim.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_dim.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_exp.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_exp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_imag.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_imag.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_int.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_int.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_lg10.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_lg10.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_log.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_log.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_mod.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_mod.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_nint.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_nint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_prod.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_prod.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_sign.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_sin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_sin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_sinh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_sinh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_sqrt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_sqrt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_tan.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_tan.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/d_tanh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/d_tanh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/derf_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/derf_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/derfc_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/derfc_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dfe.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/dfe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dolio.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/dolio.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/dtime_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/dtime_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/due.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/due.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ef1asc_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/ef1asc_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ef1cmc_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/ef1cmc_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/endfile.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/endfile.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/erf_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/erf_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/erfc_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/erfc_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/err.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/err.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/etime_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/etime_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/exit_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/exit_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/f77_aloc.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/f77_aloc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/f77vers.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/f77vers.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fmt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/fmt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fmtlib.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/fmtlib.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ftell_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/ftell_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getarg_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/getarg_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/getenv_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/getenv_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_dim.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_dim.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_dnnt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_dnnt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_indx.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_indx.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_len.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_len.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_mod.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_mod.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_nint.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_nint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/h_sign.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/h_sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hl_ge.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/hl_ge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hl_gt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/hl_gt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hl_le.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/hl_le.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hl_lt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/hl_lt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i77vers.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i77vers.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_ceiling.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_ceiling.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_dim.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_dim.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_dnnt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_dnnt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_indx.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_indx.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_len.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_len.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_len_trim.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_len_trim.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_mod.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_mod.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_nint.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_nint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/i_sign.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/i_sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/iargc_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/iargc_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/iio.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/iio.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ilnw.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/ilnw.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/inquire.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/inquire.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/l_ge.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/l_ge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/l_gt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/l_gt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/l_le.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/l_le.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/l_lt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/l_lt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lbitbits.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/lbitbits.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lbitshft.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/lbitshft.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lread.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/lread.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/lwrite.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/lwrite.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/main.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/open.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/open.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_ci.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_ci.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_dd.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_dd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_di.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_di.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_hh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_hh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_ii.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_ii.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_ri.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_ri.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_zi.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_zi.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pow_zz.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/pow_zz.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_acos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_acos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_asin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_asin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_atan.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_atan.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_atn2.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_atn2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_cnjg.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_cnjg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_cos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_cos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_cosh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_cosh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_dim.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_dim.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_exp.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_exp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_imag.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_imag.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_int.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_int.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_lg10.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_lg10.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_log.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_log.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_mod.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_mod.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_nint.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_nint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_sign.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_sign.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_sin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_sin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_sinh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_sinh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_sqrt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_sqrt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_tan.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_tan.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/r_tanh.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/r_tanh.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rdfmt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/rdfmt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rewind.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/rewind.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rsfe.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/rsfe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rsli.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/rsli.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rsne.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/rsne.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_cat.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_cat.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_cmp.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_cmp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_copy.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_copy.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_paus.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_paus.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_rnge.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_rnge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/s_stop.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/s_stop.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sfe.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/sfe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sig_die.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/sig_die.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/signal_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/signal_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/signbit.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/signbit.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sue.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/sue.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/system_.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/system_.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/typesize.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/typesize.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uio.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/uio.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/uninit.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/uninit.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/util.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/util.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wref.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/wref.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wrtfmt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/wrtfmt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wsfe.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/wsfe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wsle.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/wsle.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/wsne.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/wsne.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/xwsne.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/xwsne.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_abs.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_abs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_cos.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_cos.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_div.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_div.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_exp.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_exp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_log.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_log.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_sin.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_sin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/z_sqrt.o: ../../third/clapack-3.2.1/F2CLIBS/libf2c/z_sqrt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif