// ---------------------------------------------------------------------
// This agent file is auto-generated by behaviac designer, but you should
// implement the methods of the agent class if necessary!
// ---------------------------------------------------------------------

#include "CommonAgent.h"
#include "script/IFunctionInvoker.h"
#include "TreeTemplate.h"

using namespace hbtf;
CommonAgent::CommonAgent()
{
}

CommonAgent::~CommonAgent()
{
}

BEGIN_PROPERTIES_DESCRIPTION(CommonAgent)
{
    // CLASS_DISPLAYNAME(L"CommonAgent");
    CLASS_DESC(L"Justs Common Agent");

    REGISTER_METHOD(Method0);
    REGISTER_METHOD(Method1);
    REGISTER_METHOD(Method2);
    REGISTER_METHOD(Method3);
    REGISTER_METHOD(Method4);
    REGISTER_METHOD(Method5);
    REGISTER_METHOD(Method6);
    REGISTER_METHOD(Method7);
    REGISTER_METHOD(Method8);
    REGISTER_METHOD(Method9);
    REGISTER_METHOD(Method10);
    REGISTER_METHOD(Method11);
    REGISTER_METHOD(Method12);
    REGISTER_METHOD(Method13);
    REGISTER_METHOD(Method14);
    REGISTER_METHOD(Method15);
    REGISTER_METHOD(Method16);
    REGISTER_METHOD(Method17);
    REGISTER_METHOD(Method18);
    REGISTER_METHOD(Method19);
    REGISTER_METHOD(Method20);
    REGISTER_METHOD(Method21);
    REGISTER_METHOD(Method22);
    REGISTER_METHOD(Method23);
    REGISTER_METHOD(Method24);
    REGISTER_METHOD(Method25);
    REGISTER_METHOD(Method26);
    REGISTER_METHOD(Method27);
    REGISTER_METHOD(Method28);
    REGISTER_METHOD(Method29);
    REGISTER_METHOD(Method30);

    REGISTER_METHOD(Condition0);
    REGISTER_METHOD(Condition1);
    REGISTER_METHOD(Condition2);
    REGISTER_METHOD(Condition3);
    REGISTER_METHOD(Condition4);
    REGISTER_METHOD(Condition5);
    REGISTER_METHOD(Condition6);
    REGISTER_METHOD(Condition7);
    REGISTER_METHOD(Condition8);
    REGISTER_METHOD(Condition9);
    REGISTER_METHOD(Condition10);
    REGISTER_METHOD(Condition11);
    REGISTER_METHOD(Condition12);
    REGISTER_METHOD(Condition13);
    REGISTER_METHOD(Condition14);
    REGISTER_METHOD(Condition15);
    REGISTER_METHOD(Condition16);
    REGISTER_METHOD(Condition17);
    REGISTER_METHOD(Condition18);
    REGISTER_METHOD(Condition19);
    REGISTER_METHOD(Condition20);
    REGISTER_METHOD(Condition21);
    REGISTER_METHOD(Condition22);
    REGISTER_METHOD(Condition23);
    REGISTER_METHOD(Condition24);
    REGISTER_METHOD(Condition25);
    REGISTER_METHOD(Condition26);
    REGISTER_METHOD(Condition27);
    REGISTER_METHOD(Condition28);
    REGISTER_METHOD(Condition29);
    REGISTER_METHOD(Condition30);

    REGISTER_METHOD(Action0);
    REGISTER_METHOD(Action1);
    REGISTER_METHOD(Action2);
    REGISTER_METHOD(Action3);
    REGISTER_METHOD(Action4);
    REGISTER_METHOD(Action5);
    REGISTER_METHOD(Action6);
    REGISTER_METHOD(Action7);
    REGISTER_METHOD(Action8);
    REGISTER_METHOD(Action9);
    REGISTER_METHOD(Action10);
    REGISTER_METHOD(Action11);
    REGISTER_METHOD(Action12);
    REGISTER_METHOD(Action13);
    REGISTER_METHOD(Action14);
    REGISTER_METHOD(Action15);
    REGISTER_METHOD(Action16);
    REGISTER_METHOD(Action17);
    REGISTER_METHOD(Action18);
    REGISTER_METHOD(Action19);
    REGISTER_METHOD(Action20);
    REGISTER_METHOD(Action21);
    REGISTER_METHOD(Action22);
    REGISTER_METHOD(Action23);
    REGISTER_METHOD(Action24);
    REGISTER_METHOD(Action25);
    REGISTER_METHOD(Action26);
    REGISTER_METHOD(Action27);
    REGISTER_METHOD(Action28);
    REGISTER_METHOD(Action29);
    REGISTER_METHOD(Action30);
}
END_PROPERTIES_DESCRIPTION()

void CommonAgent::Method0()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 0, m_rpResponse, "Unknown Method0");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method1()
{
	hc::IFunctionInvoker* f = 
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 1, m_rpResponse, "Unknown Method1");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method2()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 2, m_rpResponse, "Unknown Method2");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method3()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 3, m_rpResponse, "Unknown Method3");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method4()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 4, m_rpResponse, "Unknown Method4");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method5()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 5, m_rpResponse, "Unknown Method5");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method6()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 6, m_rpResponse, "Unknown Method6");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method7()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 7, m_rpResponse, "Unknown Method7");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method8()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 8, m_rpResponse, "Unknown Method8");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method9()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 9, m_rpResponse, "Unknown Method9");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method10()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 10, m_rpResponse, "Unknown Method10");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method11()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 11, m_rpResponse, "Unknown Method11");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method12()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 12, m_rpResponse, "Unknown Method12");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method13()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 13, m_rpResponse, "Unknown Method13");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method14()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 14, m_rpResponse, "Unknown Method14");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method15()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 15, m_rpResponse, "Unknown Method15");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method16()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 16, m_rpResponse, "Unknown Method16");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method17()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 17, m_rpResponse, "Unknown Method17");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method18()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 18, m_rpResponse, "Unknown Method18");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method19()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 19, m_rpResponse, "Unknown Method19");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method20()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 20, m_rpResponse, "Unknown Method20");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method21()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 21, m_rpResponse, "Unknown Method21");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method22()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 22, m_rpResponse, "Unknown Method22");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method23()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 23, m_rpResponse, "Unknown Method23");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method24()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 24, m_rpResponse, "Unknown Method24");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method25()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 25, m_rpResponse, "Unknown Method25");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method26()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 26, m_rpResponse, "Unknown Method26");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method27()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 27, m_rpResponse, "Unknown Method27");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method28()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 28, m_rpResponse, "Unknown Method28");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method29()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 29, m_rpResponse, "Unknown Method29");
	f->Invoke(&m_rpResponse);
}
void CommonAgent::Method30()
{
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_METHOD_BEGIN + 30, m_rpResponse, "Unknown Method30");
	f->Invoke(&m_rpResponse);
}

bool CommonAgent::Condition0()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 0, m_rpResponse, "Unknown Condition0");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition1()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 1, m_rpResponse, "Unknown Condition1");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition2()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 2, m_rpResponse, "Unknown Condition2");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition3()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 3, m_rpResponse, "Unknown Condition3");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition4()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 4, m_rpResponse, "Unknown Condition4");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition5()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 5, m_rpResponse, "Unknown Condition5");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition6()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 6, m_rpResponse, "Unknown Condition6");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition7()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 7, m_rpResponse, "Unknown Condition7");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition8()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 8, m_rpResponse, "Unknown Condition8");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition9()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 9, m_rpResponse, "Unknown Condition9");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition10()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 10, m_rpResponse, "Unknown Condition10");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition11()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 11, m_rpResponse, "Unknown Condition11");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition12()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 12, m_rpResponse, "Unknown Condition12");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition13()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 13, m_rpResponse, "Unknown Condition13");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition14()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 14, m_rpResponse, "Unknown Condition14");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition15()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 15, m_rpResponse, "Unknown Condition15");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition16()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 16, m_rpResponse, "Unknown Condition16");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition17()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 17, m_rpResponse, "Unknown Condition17");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition18()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 18, m_rpResponse, "Unknown Condition18");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition19()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 19, m_rpResponse, "Unknown Condition19");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition20()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 20, m_rpResponse, "Unknown Condition20");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition21()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 21, m_rpResponse, "Unknown Condition21");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition22()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 22, m_rpResponse, "Unknown Condition22");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition23()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 23, m_rpResponse, "Unknown Condition23");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition24()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 24, m_rpResponse, "Unknown Condition24");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition25()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 25, m_rpResponse, "Unknown Condition25");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition26()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 26, m_rpResponse, "Unknown Condition26");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition27()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 27, m_rpResponse, "Unknown Condition27");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition28()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 28, m_rpResponse, "Unknown Condition28");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition29()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 29, m_rpResponse, "Unknown Condition29");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
bool CommonAgent::Condition30()
{
	bool res;
	bool* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_CONDITION_BEGIN + 30, m_rpResponse, "Unknown Condition30");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}


behaviac::EBTStatus CommonAgent::Action0()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 0, m_rpResponse, "Unknown Action0");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action1()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 1, m_rpResponse, "Unknown Action1");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action2()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 2, m_rpResponse, "Unknown Action2");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action3()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 3, m_rpResponse, "Unknown Action3");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action4()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 4, m_rpResponse, "Unknown Action4");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action5()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 5, m_rpResponse, "Unknown Action5");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action6()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 6, m_rpResponse, "Unknown Action6");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action7()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 7, m_rpResponse, "Unknown Action7");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action8()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 8, m_rpResponse, "Unknown Action8");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action9()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 9, m_rpResponse, "Unknown Action9");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action10()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 10, m_rpResponse, "Unknown Action10");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action11()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 11, m_rpResponse, "Unknown Action11");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action12()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 12, m_rpResponse, "Unknown Action12");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action13()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 13, m_rpResponse, "Unknown Action13");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action14()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 14, m_rpResponse, "Unknown Action14");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action15()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 15, m_rpResponse, "Unknown Action15");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action16()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 16, m_rpResponse, "Unknown Action16");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action17()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 17, m_rpResponse, "Unknown Action17");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action18()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 18, m_rpResponse, "Unknown Action18");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action19()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 19, m_rpResponse, "Unknown Action19");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action20()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 20, m_rpResponse, "Unknown Action20");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action21()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 21, m_rpResponse, "Unknown Action21");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action22()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 22, m_rpResponse, "Unknown Action22");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action23()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 23, m_rpResponse, "Unknown Action23");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action24()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 24, m_rpResponse, "Unknown Action24");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action25()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 25, m_rpResponse, "Unknown Action25");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action26()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 26, m_rpResponse, "Unknown Action26");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action27()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 27, m_rpResponse, "Unknown Action27");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action28()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 28, m_rpResponse, "Unknown Action28");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action29()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 29, m_rpResponse, "Unknown Action29");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}
behaviac::EBTStatus CommonAgent::Action30()
{
	behaviac::EBTStatus res;
	behaviac::EBTStatus* pres = &res;
	hc::IFunctionInvoker* f =
		_GetFunction(TreeTemplate::BTC_ACTION_BEGIN + 30, m_rpResponse, "Unknown Action30");
	f->Invoke(&pres, &m_rpResponse);
	return res;
}


